import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Anuruththan's Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <link rel="icon" href="/anuru_logo_final.png" sizes="any" />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
